AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for Taim Customer Service

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  TaimCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.taim.taimcustomerservicelambda.handlers.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/taimcustomerservicelambda-1.0.0-SNAPSHOT-lambda-package.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  TaimBackendServiceLambdaCustomerApi:
    Description: Customer Url For Taim Customer Service
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Beta/customers'
    Export:
      Name: TaimBackendServiceLambdaCustomerApi